# Generated by Django 3.0.5 on 2020-10-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('flood_depth', models.IntegerField(null=True)),
                ('latitude', models.CharField(max_length=12, null=True)),
                ('longitude', models.CharField(max_length=13, null=True)),
                ('time_stamp', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('additional_info', models.TextField(null=True)),
            ],
        ),
    ]
